ethpandaops/ethereum-package

docs/changelog.md
src/forkmon/forkmon_launcher.star
src/grafana/grafana_launcher.star
src/participant_network/prelaunch_data_generator/cl_genesis/cl_genesis_data_generator.star
src/participant_network/prelaunch_data_generator/el_genesis/el_genesis_data_generator.star
src/prometheus/prometheus_launcher.star

Depends on https://github.com/kurtosis-tech/kurtosis/pull/455

pass dicts/structs to render_templates

---

.circleci/config.yml
docs/changelog.md
main.star

https://github.com/kurtosis-tech/kurtosis/issues/425

replace main() with run()

---

.circleci/config.yml
main.star
src/forkmon/forkmon_launcher.star
src/grafana/grafana_launcher.star
src/participant_network/cl/cl_node_health_checker.star
src/participant_network/cl/lighthouse/lighthouse_launcher.star
src/participant_network/cl/lodestar/lodestar_launcher.star
src/participant_network/cl/nimbus/nimbus_launcher.star
src/participant_network/cl/prysm/prysm_launcher.star
src/participant_network/cl/teku/teku_launcher.star
src/participant_network/el/besu/besu_launcher.star
src/participant_network/el/el_admin_node_info.star
src/participant_network/el/erigon/erigon_launcher.star
src/participant_network/el/geth/geth_launcher.star
src/participant_network/el/nethermind/nethermind_launcher.star
src/participant_network/mev_boost/mev_boost_launcher.star
src/participant_network/participant_network.star
src/participant_network/prelaunch_data_generator/cl_genesis/cl_genesis_data_generator.star
src/participant_network/prelaunch_data_generator/cl_validator_keystores/cl_validator_keystore_generator.star
src/participant_network/prelaunch_data_generator/el_genesis/el_genesis_data_generator.star
src/participant_network/prelaunch_data_generator/prelaunch_data_generator_launcher/prelaunch_data_generator_launcher.star
src/prometheus/prometheus_launcher.star
src/testnet_verifier/testnet_verifier.star
src/transaction_spammer/transaction_spammer.star

BREAKING-CHANGE: Uses the `plan` object. Users will have to update their Kurtosis CLI to >= 0.63.0 and restart the engine

fix!: Use plan object

---

main.star
src/forkmon/forkmon_launcher.star
src/grafana/grafana_launcher.star
src/participant_network/cl/cl_client_context.star
src/participant_network/cl/cl_node_health_checker.star
src/participant_network/cl/lighthouse/lighthouse_launcher.star
src/participant_network/cl/lodestar/lodestar_launcher.star
src/participant_network/cl/nimbus/nimbus_launcher.star
src/participant_network/cl/prysm/prysm_launcher.star
src/participant_network/cl/teku/teku_launcher.star
src/participant_network/el/besu/besu_launcher.star
src/participant_network/el/el_admin_node_info.star
src/participant_network/el/erigon/erigon_launcher.star
src/participant_network/el/geth/geth_launcher.star
src/participant_network/el/nethermind/nethermind_launcher.star
src/participant_network/mev_boost/mev_boost_launcher.star
src/participant_network/participant_network.star
src/participant_network/prelaunch_data_generator/cl_genesis/cl_genesis_data_generator.star
src/participant_network/prelaunch_data_generator/cl_validator_keystores/cl_validator_keystore_generator.star
src/participant_network/prelaunch_data_generator/el_genesis/el_genesis_data_generator.star
src/participant_network/prelaunch_data_generator/prelaunch_data_generator_launcher/prelaunch_data_generator_launcher.star
src/prometheus/prometheus_launcher.star
src/testnet_verifier/testnet_verifier.star
src/transaction_spammer/transaction_spammer.star

Can be merged after `service-name` gets merged.

fix: make this work with kurtosis 0.65.0

---

README.md
docs/architecture.md
src/participant_network/el/geth/geth_launcher.star
src/participant_network/el/nethermind/nethermind_launcher.star
src/participant_network/prelaunch_data_generator/prelaunch_data_generator_launcher/prelaunch_data_generator_launcher.star

this is a clone of this PR: https://github.com/kurtosis-tech/eth2-package/pull/92
Fixes #91

fix: geth failing after ethash package removal

---

src/grafana/grafana_launcher.star
static_files/grafana-config/dashboards/default.json

feat: disable login for grafana

feat: disable login for grafana

---

README.md

docs: enrich docs about mev

---

src/package_io/parse_input.star

fix: make besu a bootnode

---

src/light_beaconchain/light_beaconchain_launcher.star
static_files/light-beaconchain-config/config.yaml.tmpl

feat: add multiple endpoint support for lightbeaconchain expolorer

feat: add multiple endpoint support for lightbeaconchain expolorer

---

.circleci/config.yml
.circleci/tests/ethereumjs-all.json
.circleci/tests/full-interop.json
.circleci/tests/lighthouse-all.json
.circleci/tests/lodestar-all.json
.circleci/tests/nimbus-all.json
.circleci/tests/prysm-all.json
.circleci/tests/teku-all.json

feat: add ethereumjs to nightly runners

feat: add ethereumjs to nightly runners

---

src/mev_relay/mev_relay_launcher.star

Uses the latest Redis, and DRYs out duplicated Postgres & Redis values

fix: Kevin/unpin redis version

---

main.star
src/mock_mev/mock_mev_launcher.star
src/package_io/parse_input.star

Required changes for the latest version of the mock builder.
cc @parithosh

fix: Mock builder updates

---

src/testnet_verifier/testnet_verifier.star

Will fail till we merge a breaking change with the above migration. This PR is on standby.

fix: replace plan.assert with plan.verify

---

network_params.json

- reduce capella fork epoch to 0 from 2
- indent mev_params for easier readability
- add "mev_flood_seconds_per_bundle": 15,
- add "launch_custom_flood": false

docs: update default network_params.json file

---

main.star
src/prometheus/prometheus_launcher.star

Added el_client_contexts to launch_prometheus

feat: all_el_metrics

---

src/transaction_spammer/transaction_spammer.star

this is another change we added while fixing merge conflicts today

fix: use 4th private key (index 3) for tx fuzz like before

---

src/package_io/parse_input.star

```json
{
"participants": [
{
"el_client_type": "geth",
"el_client_image": "ethpandaops/geth:lightclient-devnet-8-edf4ab3",
"cl_client_type": "lighthouse",
"cl_client_image": "sigp/lighthouse:deneb",
"count": 1
},
{
"el_client_type": "geth",
"el_client_image": "ethpandaops/geth:lightclient-devnet-8-edf4ab3",
"cl_client_type": "teku",
"cl_client_image": "consensys/teku:develop",
"count": 3
}
]
}
```
Sample input would misbehave before this fix

fix: bug with participant counts that lead to more than needed participants

---

src/mev_relay/mev_relay_launcher.star

We will be make persist True in the base package

fix: explicitly set persist to false

---

.circleci/config.yml
.circleci/tests/mev.json
.circleci/tests/mix-with-tools.json
main.star
src/package_io/parse_input.star

fix: use 0.27 as the mev boost image
fix: use ethpandaops/erigon as its multiarch

ci: fix nightly test

---

src/full_beaconchain/full_beaconchain_launcher.star

tested locally on digital ocean

fix: big table spin up logic for k8s

---

src/prelaunch_data_generator/el_cl_genesis/el_cl_genesis_generator.star

was running into the same bug as a few months ago -  https://github.com/flashbots/mev-boost-relay/issues/507

fix: genesis validators root had an extra new line

---

README.md
main.star
network_params.yaml
src/blob_spammer/blob_spammer.star
src/broadcaster/broadcaster.star
src/transaction_spammer/transaction_spammer.star

https://github.com/NethermindEth/broadcaster

feat: Add broadcaster

---

src/cl/lighthouse/lighthouse_launcher.star
src/cl/lodestar/lodestar_launcher.star
src/cl/nimbus/nimbus_launcher.star
src/cl/prysm/prysm_launcher.star
src/cl/teku/teku_launcher.star

fix: fixing too long graffitis

---

src/el/nethermind/nethermind_launcher.star
src/package_io/input_parser.star

Fixing this: https://github.com/NethermindEth/nethermind/pull/6528/

fix: Update nethermind to expose host on 0.0.0.0

---

static_files/assertoor-config/config.yaml.tmpl

enable new assertoor api for easier integration with other tools

feat: enable api in assertoor config

---

README.md

This config with mixed Grandine BN <> Lighthouse VC, Grandine BN <> Teku VC passes:
```
participants:
- el_type: erigon
cl_type: grandine
cl_image: grandine:local
use_separate_vc: true
vc_type: lighthouse
vc_image: sigp/lighthouse:latest
- el_type: geth
cl_type: grandine
cl_image: grandine:local
use_separate_vc: true
vc_type: teku
vc_image: consensys/teku:latest
- el_type: reth
cl_type: grandine
cl_image: grandine:local
use_separate_vc: true
vc_type: lighthouse
vc_image: sigp/lighthouse:latest
count: 1
deneb_fork_epoch: 1
min_validator_withdrawability_delay: 1
shard_committee_period: 1
num_validator_keys_per_node: 250
launch_additional_services: true
additional_services:
- dora
- assertoor
#snooper_enabled: true
disable_peer_scoring: true
assertoor_params:
image: …
```

fix: Updated Readme with VCs supported by Grandine BN

---

src/prometheus/prometheus_launcher.star

Updates prom launcher to pass in custom name after https://github.com/kurtosis-tech/prometheus-package/pull/4

fix: update prometheus api

---

src/participant_network.star

Address #653 
Adds 0-padding and indexes at 1 for vc_count.

fix: seperate vc service names

---

src/network_launcher/ephemery.star

update ephemery genesis loader to use latest `network-config.tar.gz` from ephemery genesis repository

fix: ephemery genesis loader

---

src/blobscan/blobscan_launcher.star

These new images are much more optimized and are ten times lighter (https://github.com/Blobscan/blobscan/pull/390)

chore: Update blobscan docker images

---

static_files/grafana-config/dashboards/lighthouse-peerdas-dashboard.json

Grafana dashboard for monitoring Lighthouse PeerDAS metrics.

feat: Add Lighthouse PeerDAS Dashboard

---

static_files/dora-config/config.yaml.tmpl

feat: enable dora pprof

---

static_files/assertoor-config/tests/validator-lifecycle-test.yaml

update the built int validator-lifecycle-test for assertoor

fix: built in validator lifecycle test for assertoor

---

static_files/assertoor-config/tests/all-opcodes-transaction-test.yaml
static_files/assertoor-config/tests/blob-transactions-test.yaml
static_files/assertoor-config/tests/block-proposal-check.yaml
static_files/assertoor-config/tests/eoa-transactions-test.yaml
static_files/assertoor-config/tests/stability-check.yaml

update built in assertoor tests for compatibility with recent assertoor changes:
* add unique id to all tests

fix: update built in assertoor tests

---

.github/workflows/nightly.yml
.github/workflows/per-pr.yml

Reverts ethpandaops/ethereum-package#701
Depends on https://github.com/kurtosis-tech/kurtosis/pull/2560

feat: add docker authentication

---

README.md

This PR elaborates what the `snooper_elabed` flag does.

chore: elaborate `snooper_elabed` flag description

---

static_files/mev/flashbots/mev_builder/config.toml.tmpl

Update config for newer versions of rbuilder.

fix: Update config.toml.tmpl

---

.github/tests/mix-with-tools.yaml
src/blobscan/blobscan_launcher.star

fix: add blobscan DIRECT_URL env var

---

src/shared_utils/shared_utils.star

fixes: https://github.com/ethpandaops/ethereum-package/actions/runs/14436146719/job/40477476124#step:5:479

fix: yeet trailing comma from enr list

---

.github/tests/mix-public.yaml
README.md
network_params.yaml
src/package_io/constants.star

fix: bump ethereum-genesis-generator to fix issues with large additional contracts

---

src/prometheus/prometheus_launcher.star

depends on https://github.com/kurtosis-tech/prometheus-package/pull/19

fix: revert prometheus branch

---

src/cl/prysm/prysm_launcher.star

Fixing: `grpc: error while marshaling: string field contains invalid UTF-8`

fix: prysm gzip encoding bug

---

README.md
network_params.yaml
src/package_io/constants.star

depends on https://github.com/ethpandaops/ethereum-genesis-generator/pull/225

fix: yeet-7907
