src/forkmon/forkmon_launcher.star
src/grafana/grafana_launcher.star
src/participant_network/participant_network.star
src/participant_network/prelaunch_data_generator/cl_genesis/cl_genesis_data_generator.star
src/participant_network/prelaunch_data_generator/cl_validator_keystores/cl_validator_keystore_generator.star
src/participant_network/prelaunch_data_generator/el_genesis/el_genesis_data_generator.star
src/prometheus/prometheus_launcher.star

fix: use named artifacts

---

main.star
src/participant_network/cl/cl_node_health_checker.star
src/participant_network/cl/lighthouse/lighthouse_launcher.star
src/participant_network/cl/lodestar/lodestar_launcher.star
src/participant_network/cl/nimbus/nimbus_launcher.star
src/participant_network/cl/prysm/prysm_launcher.star
src/participant_network/cl/teku/teku_launcher.star
src/participant_network/el/el_admin_node_info.star
src/participant_network/prelaunch_data_generator/cl_genesis/cl_genesis_data_generator.star
src/participant_network/prelaunch_data_generator/cl_validator_keystores/cl_validator_keystore_generator.star
src/participant_network/prelaunch_data_generator/el_genesis/el_genesis_data_generator.star
src/testnet_verifier/testnet_verifier.star

@parithosh I'll merge this PR because you can run the previous version executing the previous version like this `kurtosis run github.com/kurtosis-tech/eth2-package@0fdb74368d5611c062960c71d3d1318cce70382a`

refactor: Moved service name field from recipes to the instructions arguments

---

src/package_io/parse_input.star

This PR changes the way we count the actual number of validators by summing `count`s for each participant and multiplying by the number of validator keys per node.
Resolves https://github.com/kurtosis-tech/eth2-package/issues/111
feat: counting by summing each participant

feat: counting by summing each participant

---

README.md

fix: move parallel keystore generation to global config

fix: move parallel keystore generation to global config

---

src/mev_relay/mev_relay_launcher.star

The Postgres package always pulls the latest from `master`, meaning any breaking changes to it will immediately break this package. This pins the Postgres version in preparation for a breaking change

fix: pin postgres package

---

README.md
network_params.json

This pull request adds the following:
- [readme] verkle example configuration from: https://notes.ethereum.org/@parithosh/kurtosis-example
- [readme] mock-mev example configuration from: https://notes.ethereum.org/@parithosh/kurtosis-example
- [readme] Adds a paragraph about common debugging and management commands (logs, shell, export genesis files)
- Adds an example network_params.json file with update images for mev-relay and mev-flood. This network_params.json file contains the default parameters

docs: update readme configs & add more examples

---

main.star

Makes the `args` argument to `main.star#run` optional, so that this is even easier to import in other code chunks

feat: Make args optional

---

README.md
src/package_io/parse_input.star

fixes MEV params post https://github.com/kurtosis-tech/eth-network-package/pull/128

fix: pass through env var now for builder_signing_tx_key

---

README.md
main.star
src/package_io/parse_input.star
src/transaction_spammer/transaction_spammer.star

PR adds a possibility to push custom params to Tx_Spammer.
tested with flag --txcount=100 - Looking at Tx_Spammer logs change is applied.
Also addressing #168

feat: Add Tx_spamer_params and move MEV to the bottom of main.star

---

main.star
src/package_io/parse_input.star

I believe mev contract deployment breaks when tx-fuzz starts first as transactions are reported as underpriced

fix: dont wait for epoch 1 and launch MEV before tx-fuzz

---

main.star

if someone explicitly sets capella we can have breaks for the default seconds per slot as seen by @bharath-123 . I am wondering my `protocolberg` example goes through, I am guessing that reaches epoch 1 as the seconds per slot ar elower

fix: bring back wait for capella fork epoch

---

README.md

the example network_params.json in the readme is invalid json due to the trailing commas. This PR removes the trailing commas.

docs: fix example json due to trailing commas

---

.circleci/config.yml
.circleci/tests/disable-peer-scording.json
.circleci/tests/disable-peer-scoring.json
README.md
src/package_io/parse_input.star

feat: add "disable_peer_scoring" global flag

---

main.star
src/package_io/input_parser.star

Fixes:
* Change Mev boost Builder metrics flags. Using `--metrics.builder=true` cause this flag to be considered as `false` and making builder metrics to not being recorded.
* Fix early return on https://github.com/kurtosis-tech/ethereum-package/blob/main/main.star#L236-L242 causing the execution to finish before adding the additional services.

fix: wrong builder metrics flag

---

src/el/geth/geth_launcher.star

as new args were added to geth the hardcoded indexes are not configured properly. This makes cmd args for builder more robust.

fix: builder args incorrectly configured

---

README.md

this PR adds pk910 and sam from the Ethereum Foundation to the list of maintainers in the package's readme.

docs: update list of maintainers in readme

---

README.md
network_params.yaml
src/package_io/input_parser.star
src/participant_network.star

This PR allows you to set network_params.preregistered_validator_count. If not set, or set to 0 the original behavior of calculating the total validators via summing the staked participants is applied.

feat: add preregistered_validator_count network param field

---

src/blob_spammer/blob_spammer.star

I'm constantly getting OOM on the `blob-spammer` container, as it's regularly exceeding 300mb memory usage, and it usually only survives for a few seconds.
Bumping the `MAX_MEMORY` up prevents this from happening.
Docker resource usage graph:

fix: increase memory for blob spammer to prevent container from getting OOM killed

---

src/el/geth/geth_launcher.star

Very minor addition to enable running suave-enabled geth (a.k.a. `suave-execution-geth`) instead of the stock geths.

feat: Add suave-enabled geth support

---

README.md
src/assertoor/assertoor_launcher.star
static_files/assertoor-config/config.yaml.tmpl

This adds the ability do use complex objects as test configs that are passed through to the assertoor config in json format.
It allows defining assertoor tests like this via the kurtosis params:
```
assertoor_params:
run_stability_check: false
run_block_proposal_check: true
tests:
- file: https://raw.githubusercontent.com/ethpandaops/assertoor-test/master/assertoor-tests/block-proposal-check.yaml
timeout: 2h
config:
someCustomTestConfig: "some value"
```
The old way to specify the link to the test only is still supported:
```
assertoor_params:
run_stability_check: false
run_block_proposal_check: true
tests:
- "https://raw.githubusercontent.com/ethpandaops/assertoor-test/master/assertoor-tests/block-proposal-check.yaml"
```
Effectively both formats can be used.
The downstream …

feat: allow more detailed additional test configurations in assertoor_params

---

.github/tests/dencun-devnet-12.yaml
.github/tests/dencun-genesis.yaml
.github/tests/ephemery.yaml
.github/tests/mev.yaml
.github/tests/mix-persistence-k8s.yaml
.github/tests/mix-persistence.yaml
.github/tests/mix-with-tools-mev.yaml
.github/tests/sepolia-mix.yaml
.github/tests/split-nimbus.yaml
src/package_io/input_parser.star
src/participant_network.star

This PR ensures that the validator image will be the same as CL image (if one is defined) and only fallback to the default validator image if there is no validator image nor beacon image is defined.

fix: use the cl as the default validator image if none are defined

---

src/prelaunch_data_generator/validator_keystores/validator_ranges_generator.star

The ranges.yaml currently looks like this:
```
0-250: cl-1-lighthouse-geth
250-500: cl-2-prysm-reth
500-750: cl-3-lodestar-besu
```
but the end index should be inclusive:
```
0-249: cl-1-lighthouse-geth
250-499: cl-2-prysm-reth
500-749: cl-3-lodestar-besu
```

fix: fix end index in validator ranges file

---

src/assertoor/assertoor_launcher.star

assertoor config still had a few names in old format, this replaces them with the new format

fix: use new validator names in assertoor config

---

src/assertoor/assertoor_launcher.star
src/dora/dora_launcher.star

Verkle support has been dropped from the package.
Dora & Assertoor were using custom images to support verkle,  these images are now accidentally used, as electra_fork_epoch is set to 500 now by default.

fix: use correct dora & assertoor images

---

main.star
src/assertoor/assertoor_launcher.star
src/dora/dora_launcher.star

use `minimal-preset` images for dora & assertoor when minimal preset is used

fix: use `minimal-preset` images for dora & assertoor when minimal preset is used

---

.github/tests/mix-persistence.yaml

fixed the failing persistence test by re-ordering the clients list.
The test fails because initialization of all EL clients takes longer than the initial genesis delay.
Due to this, lighhouse returns an unhealty result for its health check as it's post-genesis and not following a chain / has no peers.
The kurtosis package waits for a healthy result, which never occurs as all other BNs & VCs are missing at that point.
The fix proposed in this PR is a workaround as it moves the lighthouse node further down to ensure it can connect to other nodes initialized before.
There is an alternative approach to fix this issue:
```
genesis_delay: 300
```
which ensures all clients are properly initialized before the network starts.

fix: fix failing persistence test

---

src/cl/prysm/prysm_launcher.star

This parameter is important. Prism will handle deposit logs from `--contract-deployment-block` to the latest block. If this parameter is missed, Prysm's proposed block's eth1 data will have no deposit data.
The default value is 11184524, which is used for the mainnet.
https://github.com/ethpandaops/dencun-devnets/blob/master/ansible/inventories/devnet-12/group_vars/prysm.yaml#L52C5-L52C33

fix: add --contract-deployment-block parameter for Prysm

---

src/full_beaconchain/full_beaconchain_launcher.star
src/grafana/grafana_launcher.star
src/mev/mev_custom_flood/mev_custom_flood_launcher.star
src/mev/mev_flood/mev_flood_launcher.star
src/network_launcher/devnet.star
src/network_launcher/ephemery.star
src/network_launcher/public_network.star
src/network_launcher/shadowfork.star
src/prelaunch_data_generator/el_cl_genesis/el_cl_genesis_generator.star
src/prelaunch_data_generator/validator_keystores/validator_keystore_generator.star
src/shared_utils/shared_utils.star

Add human friendly descriptions when executing commands or running scripts.
Here is an example:
Without descriptions.
```bash
Executing command on service 'validator-key-generation-cl-validator-keystore'
Command returned with exit code '0' with no output
Verifying whether two values meet a certain condition '=='
Verification succeeded. Value is '0'.
Storing files from service 'validator-key-generation-cl-validator-keystore' at path '/node-0-keystores' to files artifact with name '1-lighthouse-geth-0-63'
Files with artifact name '1-lighthouse-geth-0-63' uploaded with artifact UUID 'd42fe1052c85433580a752bf818a54f1'
Executing command on service 'validator-key-generation-cl-validator-keystore'
Command returned with exit code '0' with no output
```
With descriptions.
```bash
Generating …
```

chore: add human friendly descriptions to `exec`, `run_sh` and `run_python` instructions

---

src/el/erigon/erigon_launcher.star

Erigon will disable discovery when --chain=dev: https://github.com/ledgerwatch/erigon/blob/3323fdc3489d845e9db607ad5ccc2190421b699d/cmd/utils/flags.go#L1322-L1331   
So with the current Kurtosis startup parameter, Erigon will not connect to other EL nodes.
Therefore, I propose deleting this --chain parameter in the Starlark script. If users want, they can pass the parameter through the "el_extra_params" configuration.

fix: remove erigon's --chain parameter

---

src/assertoor/assertoor_launcher.star
src/participant.star
src/participant_network.star
static_files/assertoor-config/config.yaml.tmpl

Add URL to RPC snoopers to assertoor config when snoopers are enabled.
This will allow assertoor to use the special snooper control api for further tests

feat: add snooper urls to assertoor config

---

src/cl/cl_launcher.star

Fixes #576
Now it correctly results in the error message:
```
There was an error interpreting Starlark code 
Evaluation error: fail: Unsupported launcher 'foo', need one of 'lighthouse,lodestar,nimbus,prysm,teku,grandine'
at [github.com/kurtosis-tech/ethereum-package/main.star:104:55]: run
at [github.com/kurtosis-tech/ethereum-package/src/participant_network.star:166:34]: launch_participant_network
at [github.com/kurtosis-tech/ethereum-package/src/cl/cl_launcher.star:106:17]: launch
at [0:0]: fail
Error encountered running Starlark code.
```

fix: non-existent field access on error message

---

src/dora/dora_launcher.star
static_files/dora-config/config.yaml.tmpl

upcoming version of dora uses execution layer clients to crawl the deposit contract log.
This PR adds the execution client urls to the dora config.

feat: add execution client urls to dora config

---

.github/workflows/per-pr.yml

previously we were using github.ref which would be main for two different PRs making the concurrency group in valid
head_ref should work for on pull request events and that should be the source branch

chore: fix ci for test runs

---

src/apache/apache_launcher.star

Serves all network config files via apache under the `/network-configs/ path.
```
/network-configs/besu.json
/network-configs/boot/
/network-configs/boot_enr.txt
/network-configs/boot_enr.yaml
/network-configs/bootnode.txt
/network-configs/bootstrap_nodes.txt
/network-configs/chainspec.json
/network-configs/config.yaml
/network-configs/deploy_block.txt
/network-configs/deposit_contract.txt
/network-configs/deposit_contract_block.txt
/network-configs/deposit_contract_block_hash.txt
/network-configs/genesis.json
/network-configs/genesis.ssz
/network-configs/genesis_validators_root.txt
/network-configs/mnemonics.yaml
/network-configs/parsedBeaconState.json
/network-configs/tranches/
```

feat(apache): Serve all config files

---

src/package_io/input_parser.star

The flag `--validators-builder-registration-default-enabled` must be used when VC/BN are combined. Otherwise validators won't be registered.

fix: registration flags when using beacon node only

---

.github/tests/apache.yaml
.github/tests/mev-mock.yaml
.github/tests/mev.yaml
.github/tests/participants-matrix.yaml
.github/tests/peerdas-fork.yaml
.github/workflows/per-pr.yml
README.md
src/package_io/input_parser.star
src/participant_network.star

This PR adds a new config argument called `participants_matrix`, which allows the user to easily spin up a matrix of EL/CL combos. The `el` and `cl` keys within this argument can be fully fledged normal `participants`, so they support the exact same arguments.
For example:
```
participants_matrix:
el:
- el_type: geth
- el_type: besu
- el_type: reth
cl:
- cl_type: nimbus
```
This config would create the following participants:
- `nimbus-geth`
- `nimbus-besu`
- `nimbus-reth`
```
participants_matrix:
el:
- el_type: geth
- el_type: besu
- el_type: reth
cl:
- cl_type: nimbus
participants:
- el_type: nethermind
cl_type: lighthouse
```
This config would create the following participants:
- `nimbus-geth`
- `nimbus-besu`
- `nimbus-reth`
- `lighthouse-nethermind`
```
participants_matrix:
el:
- …
```

feat: Support participants_matrix

---

README.md
main.star
network_params.yaml
src/dora/dora_launcher.star
src/package_io/input_parser.star

Allow using a custom dora image and specifying custom env variables.
This is especially useful for early testnets that might need disabling some features via ENV vars 
(eg. `KILLSWITCH_DISABLE_SSZ_REQUESTS=true`, `KILLSWITCH_DISABLE_SSZ_ENCODING=true`)

feat: allow setting custom dora image & env variables

---

README.md

Fixes:
- network_id must be a string
- `/https:#/https:\/\//`
- None is not valid, use null
- remove trailing comma from ejection_balance
Resolves https://github.com/kurtosis-tech/ethereum-package/issues/630

fix: README has invalid configs

---

src/cl/cl_launcher.star
src/package_io/input_parser.star
src/participant_network.star

I ran into a few index out of bounds and divide by zero issues. I fixed those with what I expect is the right method. One thing I would like you to check is my change on the [participant_network.star](https://github.com/0xTylerHolmes/ethereum-package/blob/061dbec8694e78dfeb2cf9c48d351202866fd6e6/src/participant_network.star#L397)
I added a check on the `vc_context` assignment for the case where `vc_count == 0`. We would get an index out of bounds panic so I just set it to `None`. I'm unsure if there are downstream consequences but everything appears to be working on my end with that.

fix: Vc count logic

---

.github/tests/mix-with-tools-mev.yaml
.github/tests/mix-with-tools-minimal.yaml
.github/tests/mix-with-tools.yaml
README.md
main.star
src/shared_utils/shared_utils.star
src/static_files/static_files.star
src/tracoor/tracoor_launcher.star
static_files/dora-config/config.yaml.tmpl
static_files/tracoor-config/config.yaml.tmpl

cc: @samcm
min config:
```yaml
additional_services:
- tracoor
```

feat: add tracoor

---

README.md

Lodestar works with all clients now on `unstable` branch(es). 
There is just one exception which is related to publishing blocks to Nimbus BN but that's an issue with all other VCs as well and seems to be only happening when running via kurtosis as confirmed here https://github.com/status-im/nimbus-eth2/issues/6205#issuecomment-2136878086. This issue can be solved though by forcing Lodestar to publish blocks as JSON, see https://github.com/kurtosis-tech/ethereum-package/pull/664#issuecomment-2160737709.
The kurtosis config I was using
```yaml
participants:
- el_type: geth
el_image: ethereum/client-go:stable
cl_type: lodestar
cl_image: chainsafe/lodestar:next
vc_type: lighthouse
vc_image: sigp/lighthouse:latest
count: 1
- el_type: geth
el_image: ethereum/client-go:stable
cl_type: …
```

feat: update Lodestar BN <> VC compatibility

---

src/network_launcher/devnet.star
src/network_launcher/ephemery.star
src/network_launcher/public_network.star
src/network_launcher/shadowfork.star
src/package_io/input_parser.star
src/prelaunch_data_generator/el_cl_genesis/el_cl_genesis_generator.star

Fixing: 
```
Reading genesis validators root
There was an error executing Starlark code 
An error occurred executing instruction (number 20) at github.com/ethpandaops/ethereum-package/src/prelaunch_data_generator/el_cl_genesis/el_cl_genesis_generator.star[65:42]:
run_sh(name="read_genesis_validators_root", run="cat /data/genesis_validators_root.txt", files={"/data": "genesis_validators_root"}, wait=None, description="Reading genesis validators root")
Caused by: error occurred while creating a run_sh task with image: badouralix/curl-jq
Caused by: Failed registering service with name: 'read_genesis_validators_root'
Caused by: Error registering service 'read_genesis_validators_root'
Caused by: An error occurred getting attributes for the Kubernetes service for user service …
```

fix: DNS-1035 label

---

README.md

Nimbus BN is working with Lodestar VC and Prysm vc as of `ethpandaops/nimbus-eth2:unstable-85c2850`

chore: update vc matrix

---

src/package_io/input_parser.star

I noticed it is not possible to run mixed vc<>bn clients if builder / mev is enabled as it applies extra flags from other clients in `vc_extra_params` as the params are applied based on `cl_type` but it should be done based on `vc_type`.
I tested this using the [following config](https://gist.github.com/nflaig/949c8b5101127961023d89de9c206b04) with both `mev_type: mock` and `mev_type: flashbots`.

fix: correctly apply extra params if builder is enabled

---

src/cl/lodestar/lodestar_launcher.star

Would be good to have invalid ssz objects persisted by default in case there is a consensus bug or other issue. There is not much downside to this besides slight storage increase but since states / blocks are generally small on devnets this shouldn't matter, also we prune objects after some time (15 days).

feat: lodestar persists invalid ssz objects by default

---

README.md
network_params.yaml
src/package_io/input_parser.star

disable all assertoor tests by default to prevent accidentally running tests twice

fix: disable all assertoor tests by default

---

static_files/dora-config/config.yaml.tmpl

This will enable additional peer infos (ENR/Enode, etc.) to be shown on the client pages. Implemented in https://github.com/ethpandaops/dora/pull/117

feat: dora - show more infos about all peers on client pages

---

src/vc/prysm.star

Related to the deprecation of the gRPC gateway: https://github.com/prysmaticlabs/prysm/pull/14089 
Currently the `mix-with-tools.yaml` test was failing due to the keymanager being enabled: 
```
== FINISHED SERVICE 'vc-2-nethermind-prysm' LOGS ===================================
Caused by: An error occurred while waiting for all TCP and UDP ports to be open
Caused by: Unsuccessful ports check for IP '172.16.0.34' and port spec '{privatePortSpec:0xc00091a0c0}', even after '240' retries with '500' milliseconds in between retries. Timeout '2m0s' has been reached
Caused by: An error occurred while calling network address '172.16.0.34:5056' with port protocol 'TCP' and using time out '200ms'
Caused by: dial tcp 172.16.0.34:5056: connect: connection refused
Error encountered running Starlark …
```

fix: prysm gRPC removal - use http server instead for keymanager

---

src/cl/teku/teku_launcher.star

Currently `'*'` is passed to Teku, which is not correct, so I see `Not Authorized` when trying to access Teku metrics, Prometheus says that Teku is down because of 403, and Grafana metrics are empty. 
Only `*` should be passed, which is the purpose of the fix.
I don't know how to test it, so not 100% on the fix.

fix: `metrics-host-allowlist` for Teku

---

static_files/assertoor-config/config.yaml.tmpl

this adds the database section to the assertoor config.
assertoor falls back to an in memory database if the database section is left out.
however, the in memory database caused issues with dora earlier, so it's better to use a non persistent file.

fix: add database config to assertoor

---

README.md

Think the prometheus_grafana services are off by default, since I had to modify the config this way to get grafana and prometheus to start.

docs: update README grafana example config

---

src/cl/prysm/prysm_launcher.star

The default image:  `gcr.io/prysmaticlabs/prysm/beacon-chain:latest` already has the `http-` flags as per https://github.com/prysmaticlabs/prysm/pull/14089
I also swapped the ports. Instead of using 3500 for the HTTP server and 4000 for the RPC server ( which is actually prysm's default behaviour). The problem is that all the other CL clients are running their HTTP beacon API under port 4000 ( `BEACON_HTTP_PORT_NUM= 4000`) . So I think it makes sense to do the same for prysm here.

fix: swap http/grpc server ports and replace flags

---

src/cl/lighthouse/lighthouse_launcher.star

The `--http-allow-sync-stalled` flag is deprecated as of Lighthouse v5.3.0, with its behaviour being enabled by default.
In v6.0.0 we would like to remove the flag entirely, which requires removing it from Kurtosis (which we run on our CI):
- https://github.com/sigp/lighthouse/pull/6490

fix: remove deprecated http-allow-sync-stalled from LH

---

src/vc/prysm.star

There is an unnecessary port assignment in prysm validator configuration which is fixed with this PR. This was also fixed in the [keymanager fix PR](https://github.com/ethpandaops/ethereum-package/pull/789) but since the `grpc-gateway` flags are deprecated since `v5.1.1`, #789 can be closed after merging.

fix: delete unnecessary port assignment for prysm

---

.github/actions/kurtosis-install/action.yaml
.github/workflows/nightly.yml
.github/workflows/per-pr.yml
.github/workflows/run-k8s.yml

Rolling back to `1.3.1`, until the docker auth problems on `1.4.0` get fixed https://github.com/kurtosis-tech/kurtosis/pull/2579

ci: run previous kurtosis version

---

src/package_io/constants.star

config:
```yaml
network: "holesky-shadowfork"
persistent: true
```
fixes
```
There was an error interpreting Starlark code
Evaluation error: key "holesky-shadowfork" not in dict
at [github.com/ethpandaops/ethereum-package/main.star:143:55]: run
at [github.com/ethpandaops/ethereum-package/src/participant_network.star:134:48]: launch_participant_network
at [github.com/ethpandaops/ethereum-package/src/el/el_launcher.star:130:35]: launch
at [github.com/ethpandaops/ethereum-package/src/el/geth/geth_launcher.star:59:24]: launch
at [github.com/ethpandaops/ethereum-package/src/el/geth/geth_launcher.star:298:39]: get_config
Error encountered running Starlark code.
```

fix: get volume size recommendations when in shadowfork mode

---

.github/workflows/per-pr.yml

Causing:
```
Error: Cannot perform an interactive login from a non TTY device
Error: Process completed with exit code 1.
```

ci: remove unnecessary docker login

---

kurtosis.yml
src/prefunded_accounts/get_prefunded_accounts.star

**purpose:**
- fix issue when running with k8s backend, where prefunded accts services are not destroyed instantaneously and this causes 'service already exists' errors
**tests:**
original error:
```
Running ethereal to derive private keys of key 1
There was an error executing Starlark code
An error occurred executing instruction (number 9) at github.com/rebelArtists/ethereum-package/src/prefunded_accounts/get_prefunded_accounts.star[12:34]:
run_sh(name="run-ethereal-private-key", run="private_key=$(/app/ethereal hd keys --seed=\"code code code code code code code code code code code quality\" --path=\"m/44'/60'/0'/0/1\" | awk '/Private key/{print substr($NF, 3)}'); echo -n $private_key", image="wealdtech/ethereal:latest", description="Running ethereal to derive private keys of key 1") …
```

fix: prefund container suffixes for k8s

---

src/el/nethermind/nethermind_launcher.star

Fixes config file name for Nethermind:
- All *.cfg files were renamed to *.json as part of this PR: https://github.com/NethermindEth/nethermind/pull/7653
- Skipping file extension will automatically add a proper one

fix: update nethermind config option

---

.github/tests/pectra.yaml.norun
README.md

Rename `thorax` -> `erigontech` for docker hub.
Not changing the `ethpandaops/erigon:main` image which appears to be the default, changing the pectra version tho. Latest published erigon images are now multi-arch tho

fix: Update Erigon docker image repo naming

---

src/cl/prysm/prysm_launcher.star

Prysm added QUIC to their client as per https://github.com/prysmaticlabs/prysm/pull/14688 . This currently broke our runs using the master branch prysm image due to the QUIC port running on 13000 by default. Which was conflicting with the settings we were providing for the UDP port:
```sh
--p2p-quic-port value                                The QUIC port used by libp2p. (default: 13000)
--p2p-tcp-port value                                 The TCP port used by libp2p. (default: 13000)
--p2p-udp-port value                                 The UDP port used by the discovery service discv5. (default: 12000)
```
I've also added the CLI flags for it, but still commented out until a stable release is done.

fix(prysm): run p2p-udp on different port as it might conflict with the new quic port

---

src/assertoor/assertoor_launcher.star

`electra-support` as been merged into master and a new release is available too.

fix: use default image for assertoor with electra enabled

---

src/prelaunch_data_generator/genesis_constants/genesis_constants.star

fix: Private key for account 20

---

static_files/assertoor-config/config.yaml.tmpl

The root folder `/` is not writable when running as non-root user, so we move the db to the /app folder

fix: use writable path for assertoor db

---

src/assertoor/assertoor_launcher.star

bump the memory limit for assertoor to 8GB
increasing the limit is necessary to run child processes (like the execution spec tests) reliable.
the limit is for the whole container, which not only includes assertoor, but also all sub-processes launched by tests.

fix: bump assertoor memory limit to 8G

---

src/dora/dora_launcher.star

uses the `eip7732-support` branch from dora: https://github.com/ethpandaops/dora/pull/227

feat: use `eip7732-support` image for dora when eip7732 is scheduled for activation (ePBS)

---

src/package_io/input_parser.star

As currently used on pectra devnet-6
More context: https://github.com/ethpandaops/pectra-devnets/pull/79

fix: decrease lighthouse mev --prepare-payload-lookahead from 12 to 8s

---

src/vc/vc_launcher.star
src/vc/vero.star

As of `v0.9.0` Vero [requires a network to be specified as a CLI argument](https://github.com/serenita-org/vero/releases/tag/v0.9.0). This PR adds that to the Kurtosis definition for the Vero VC service.
(In case you're wondering - how did Vero not have a `--network` flag before? It used to load all the spec values from the connected beacon node(s) and would then dynamically create all necessary SSZ classes.)
I tested this manually with the `.github/tests/vero-all.yaml` config and have been using this version for the last few months while preparing for Pectra.

fix: provide `--network-custom-config-path` to Vero

---

.github/actions/docker-login/action.yaml
.github/workflows/check-typos.yml
.github/workflows/conventional-pr-title-checker.yml
.github/workflows/nightly.yml
.github/workflows/per-pr.yml
.github/workflows/run-k8s.yml

This PR updates GitHub Actions to use pinned commit hashes for better security.

chore(ci): update GitHub Actions to use pinned hashes

---

src/package_io/input_parser.star

Prometheus for some reason overrides their bugfix releases for older versions of major prom versions with `latest`, breaking everything for everyone else.

fix: prometheus shouldnt use latest

---

.github/actions/docker-login/action.yaml

This makes it more obvious if rate limits are in place. Example for an authenticated user:
```
regctl image ratelimit ubuntu:latest
{
"Remain": 0,
"Limit": 0,
"Reset": 0,
"Set": false,
"Policies": null
}
```
Or unauthenticated:
```
regctl image ratelimit ubuntu:latest
{
"Remain": 100,
"Limit": 100,
"Reset": 0,
"Set": true,
"Policies": [
"100;w=21600"
]
}
```

fix(ci): make docker rate limits appear correctly

---

docs/architecture.md

Hi! I fixed broken links in `docs/architecture.md` caused by recent changes in the repo structure.   The `participant_network/` directory was removed, so all links were updated to point directly to the correct paths in `src/`.

docs: fixed broken links in `docs/architecture.md`

---

README.md
network_params.yaml
src/package_io/input_parser.star
src/package_io/sanity_check.star
src/spamoor/spamoor.star

The CPU limit on spamoor is limiting the number of v1 blob transactions I can send on my machine (possibly because cell proofs are now computed by the transaction sender). The memory limit is a secondary issue due to the higher number of pending transactions.
I chose to parameterize max/min cpu/mem since I'd expect the appropriate max will differ per-host, but let me know if you'd suggest something different!
Tested with the below params:
```
spamoor_params:
image: ethpandaops/spamoor:latest
max_cpu: 4000
max_mem: 3000
spammers:
- scenario: blob-combined
config:
throughput: 20
sidecars: 2
max_pending: 100
blob_v1_percent: 100
rebroadcast: 0
- scenario: blob-combined
config:
throughput: 20
sidecars: 2
max_pending: 100
blob_v1_percent: 100
rebroadcast: 0
```

feat: add params to configure spamoor resource limits

---

src/spamoor/spamoor.star

The [`blob-v1`](https://github.com/ethpandaops/spamoor/pull/26) branch has been merged, and the `ethpandaops/spamoor:latest` image has been updated, so I think we can remove the `blob-v1` image now.
Tested with the following params to check that kurtosis pulled `ethpandaops/spamoor:latest` and spamoor sent v0 transactions pre-fulu and v1 transactions post-fulu:
```
electra_fork_epoch: 0
fulu_fork_epoch: 1
max_blobs_per_block_fulu: 64
target_blobs_per_block_fulu: 32
additional_services:
- dora
- spamoor
spamoor_params:
spammers:
- scenario: blobs
config:
throughput: 8
sidecars: 2
max_pending: 40
blob_v1_percent: 100
rebroadcast: 0
```

fix: use latest spamoor instead of blob-v1 for peerdas

---

src/ethereum_metrics_exporter/ethereum_metrics_exporter_launcher.star
src/participant_network.star

If persistence is enabled it will return this: 
```
eth_disk_usage_bytes{directory="/data/consensus-db"} 1.01329017e+08
eth_disk_usage_bytes{directory="/data/execution-db"} 3.865923027e+09
```

feat: add disk usage as a metric for ethereum-metrics-exporter

---

static_files/mev/flashbots/mev_builder/config.toml.tmpl

fixing: https://github.com/ethpandaops/ethereum-package/actions/runs/15296185796/job/43025772045#step:5:476

fix: rbuilder parallel safe sorting

---

main.star
src/package_io/input_parser.star
src/spamoor/spamoor.star
src/static_files/static_files.star
static_files/spamoor-config/rpc-hosts.txt.tmpl

this PRC changes the way how rpc hosts are supplied to spamoor.
the hosts file contains additional client groups, including:
* this client index
* the el name
* the cl name
all these groups are applied as separate groups in spamoor, which supports multiple groups per client since the [v1.1.5 release](https://github.com/ethpandaops/spamoor/releases/tag/v1.1.5)

feat: add more groups to spamoor clients

---

src/network_launcher/public_network.star
src/network_launcher/shadowfork.star

The `remove_service` was preventing enclave edits from working on params that contained shadowforking configs such as:
```
participants:
- el_extra_params: []
network: hoodi-shadowfork
persistent: true
```
Removing the `remove_service` allows the following edit to skip instructions that haven't changed (pulling shadowfork data, which is very time consuming) while still updating instructions that do change, like updating service config of el node to have the extra cmd arg flag:
```
participants:
- el_extra_params: ["--miner.gaslimit=78000000"]
network: hoodi-shadowfork
persistent: true
```
This is in the Kurtosis docs but it's pretty hidden:
```
It's good to callout here that a few Kurtosis instructions are fundamentally incompatible with the concept of …
```

fix: shadowfork enclave edits

---

main.star

Current logic adds `--target-peers=0` when there is only one client in the kurtosis params. However, this is also applied when we use single client with a running devnet/testnet where nodes can connect to the bootnodes from the network config. 
This PR fixes this by only adding that flag when the network is `kurtosis`.

fix: only add --target-peers=0 only when the network is kurtosis

---

README.md
main.star
network_params.yaml
src/cl/cl_launcher.star
src/cl/grandine/grandine_launcher.star
src/cl/lighthouse/lighthouse_launcher.star
src/cl/lodestar/lodestar_launcher.star
src/cl/nimbus/nimbus_launcher.star
src/cl/prysm/prysm_launcher.star
src/cl/teku/teku_launcher.star
src/el/besu/besu_launcher.star
src/el/el_launcher.star
src/el/erigon/erigon_launcher.star
src/el/ethereumjs/ethereumjs_launcher.star
src/el/ethrex/ethrex_launcher.star
src/el/geth/geth_launcher.star
src/el/nethermind/nethermind_launcher.star
src/el/nimbus-eth1/nimbus_launcher.star
src/el/reth/reth_launcher.star
src/package_io/input_parser.star
src/package_io/sanity_check.star
src/participant_network.star
src/shared_utils/shared_utils.star
src/vc/lighthouse.star
src/vc/lodestar.star
src/vc/nimbus.star
src/vc/prysm.star
src/vc/teku.star
src/vc/vc_launcher.star
src/vc/vero.star

Adds `extra_files` to the config, which provides a solution to the path of `*_extra_mounts` files not working if the path is outside of the package (Kurtosis limitation)
```
extra_files:
example.json: |
{
"test": "data",
"foo": "bar"
}
participants:
- el_type: geth
cl_type: lighthouse
vc_extra_mounts:
"/configs": "example.json"
```
This will create a file in the vc at `/configs/example.json` with the conte

feat: Extra Files for `*_extra_mounts` support

---

src/cl/lighthouse/lighthouse_launcher.star

Add service name to traces exported by Lighthouse.
Please do not merge until the new lighthouse flag PR is merged: https://github.com/sigp/lighthouse/pull/7903

feat: add telemetry service name flag to Lighthouse
